### ISSUE TITLE
there's no parseEnum

### ISSUE THREAD

**Issue by langhuihui** [gagern/nodeJavaDeserialization#2]
there's no parseEnum method

**Comment by langhuihui** [comment]
` Object.defineProperties(new String(constant),……`
will return an Object with properties "0:xxx,1:xxx,2:xxx,length:xxx".It's an bad idea

**Comment by gagern** [comment]
@langhuihui are you talking about `parseArray` or `parseEnum`? For the former I don't see `new String(constant)` as you cite it, for the latter I don't see numbered properties or `length`.

**Comment by langhuihui** [comment]
parseEnum
you just code

**Comment by gagern** [comment]
`parseEnum` is meant to return a `String` object (not a low-level string) with some additional properties. It does seem to do that just fine for me. Where do you see the problem you describe?

**Comment by langhuihui** [comment]
String Object is like that.There is no problem.
